services:
  ipca-worker-go-v2:
    container_name: ipca-worker-go-v2
    build: .
    restart: unless-stopped
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    env_file:
      - .env
    networks:
      - ipca-stack
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined

networks:
  ipca-stack:
    external: true
